### ISSUE TITLE
Plugin generated command is missing ssctoken and uptoken

### ISSUE THREAD

**Issue by fabitamas** [jenkinsci/fortify-plugin#15]
I'm trying to use the plugin to initiate a cloud scan in the following way:
`fortifyRemoteAnalysis remoteAnalysisProjectType: fortifyMaven(buildFile: ''), uploadSSC: [appName: 'my-app-name', appVersion: 'my-version']`

The generated command looks the following:
`cloudscan -sscurl <my-ssc-url> -ssctoken start -bt mvn -upload -application my-app-name -version my-version -uptoken `

It is missing the actual ssctoken and uptoken.
The command fails to execute correctly without those tokens. The tokens are configured correctly on the Manage Jenkins page.

**Comment by young-s-park** [comment]
You need to enter a CloudCtrlToken in the "Controller token" field. For a CloudScan scan, this is the token that is used, not the "Authentication token" under the SSC URL field.

**Comment by fabitamas** [comment]
Thanks for the tip, the controller token field is filled out

<img width="1016" alt="Screen Shot 2020-04-29 at 4 57 59 PM" src="https://user-images.githubusercontent.com/5854373/80646463-c10fdd00-8a3a-11ea-9ff4-57c603a1db7f.png">

**Comment by young-s-park** [comment]
hmm...haven't seen or experienced this myself. Have you tried restarting Jenkins?

**Comment by fabitamas** [comment]
No, but I cannot really restart it... It is a main production jenkins instance of the company. It works on my test instance also.

**Comment by fabitamas** [comment]
Sorry, this was a mistake from the devops team, the controller token was actually not configured correctly.
