### ISSUE TITLE
How can apply the 'Fortify Assessment' menu?

### ISSUE THREAD

**Issue by ksg97031** [jenkinsci/fortify-plugin#22]
Hi, I install and set up the last version of fortify plugin before, but I can't find the below page.
Can you tell me more information about how to apply it?

![image](https://user-images.githubusercontent.com/6715194/90603388-3136ae80-e236-11ea-8454-4652ca437bef.png)

**Comment by akaryakina** [comment]
Hi, first you need to configure SSC connection in plugin settings, then set up Fortify Assessement step for your job, and finally run the build with an fpr upload step in order to see this page. It only appears after successful build and upload.
Please, follow our video tutorial https://www.youtube.com/watch?v=cjEwDmTsxII for more details.

**Comment by ksg97031** [comment]
@akaryakina Thank you for responding!

I have configured SSC connection in plugin settings, but the only difference is that I'm not doing a local scan. I selected the option "local translate & remote scan". Is this option can't use the "Fortify Assessment" menu?

**Comment by akaryakina** [comment]
@ksg97031 It does not matter how you translate and scan, it only matters if you configured application and version for your SSC connection. The Fortify Assessment is available after it is being processed on SSC.

**Comment by ashnazg** [comment]
@akarjakina are you saying that the build can be written to submit a *remote* scan, and then _download the results in order for the Fortify Assessment to be generated_?  Our understanding was that the _plugin_ didn't have this capability natively, but we've not seen an example of remote scan results that could then be incorporated into the submitting build.
