### ISSUE TITLE
Fortify Pipeline Issue - Unable to view results in Fortify Assessment

### ISSUE THREAD

**Issue by ParthibanSG** [jenkinsci/fortify-plugin#44]
I am currently Fortify Suite environment running with 20.1 version and same goes for the Jenkins plugin version. I am able to run jenkins job with "Invoke Fortify Assessment" in Post-Build Actions and FPR gets published to SSC and I am able to view results in Jenkins as a separate hyperlink

However, when I perform the same via a pipeline to have "fortifyUpload" step, FPR gets published to SSC but I am unable to view results in Jenkins. Fortify support mentioned this as a bug since we have special characters in our Fortify Project version.

How is it possible that "Build Step" works fine with special characters whereas "Pipeline Step" doesn't? Is it really a bug or my understanding is wrong? Please let me know

**Comment by young-s-park** [comment]
Hello @ParthibanSG ! What do you see in your pipelines project after the upload is complete? Is the "Fortify Assessment (appname-version)" link visible? If so, does anything happen when you click on it? If not, are there any errors in the console or in the Jenkins logs?

**Comment by ParthibanSG** [comment]
@young-s-park After the pipeline is completed, I could see the "Fortify Assessment" hyperlink available in Jenkins job but when I click to retrieve results, I see "ERROR 404 - Not Found" in console

My fortify project naming sample is like below

App Name : Fortify Testing [1234]
Version Name : YYYY-MM-DD Fortify Sample (Testing) [1234]

**Comment by akaryakina** [comment]
@ParthibanSG It looks like the issue happens when you have square brackets in the name of your app or version. As a temporary workaround (before we release an official fix), could you generate the names and versions on SSC without brackets?

**Comment by tim-reslv** [comment]
We got below error when click the hyperlink in Fortify Assessment.

Unexpected error has occurred. Please contact your administratorJun 3, 2021 5:33:17 PM
TypeError: Cannot read property 'traceNodes' of undefined 


Got error URL link:
https://fortifyssc.sample.com:8443/ssc/html/ssc/version/10001/fix/26/?projectName=WEATHERFORECAST-API&projectVersionName=1.0&issue=B97D5FD6B9BD8340DF4AD9FF52658746&engineType=SCA

We try to remove engineType=SCA from URL, and it work without error.
Working URL:
https://fortifyssc.sample.com:8443/ssc/html/ssc/version/10001/fix/26/?projectName=WEATHERFORECAST-API&projectVersionName=1.0&issue=B97D5FD6B9BD8340DF4AD9FF52658746

**Comment by akaryakina** [comment]
Hi @ParthibanSG, we believe it should be fixed with our latest 20.2.35 service release of the plugin, could you please verify?

**Comment by akaryakina** [comment]
@tim-reslv What version of SSC are you using? It is a different issue not related to the one in the original issue description, please, open another ticket.
