### ISSUE TITLE
Jenkins 2.277.1 can't use fortify-plugin

### ISSUE THREAD

**Issue by oceangle** [jenkinsci/fortify-plugin#46]
Hi, I upgrade jenkins to version 2.277.1 and found that the project's configuration can't saved, and when I uninstall fortify-plugin then the configuration can be saved. I search fortify-plugin from jenkins 2.277.1  can't find fortify plugin, but fortify on demand plugin. How should I do? Perhaps return to low version of jenkins?

**Comment by rkivisto** [comment]
The symptom of the configuration not being able to be saved after upgrading to 2.277.1 makes me suspect this is a `tables-to-divs-regression`:
https://www.jenkins.io/doc/developer/views/table-to-div-migration/

**Comment by akaryakina** [comment]
Hi guys, we've implemented the tables-to-div conversion and are about to release a new patch release of the plugin to support the latest Jenkins 2.277.4. It's in testing right now, and we hope to release it very soon.

**Comment by camilo12369** [comment]
Hi, we are super interested. Please, do you have an ETA? Thanks!

**Comment by akaryakina** [comment]
The release should go out this week. We're putting a couple of bugfixes in.

**Comment by akaryakina** [comment]
We have released! You're welcome to use our plugin with the latest 2.289.1 version of Jenkins.
