### ISSUE TITLE
Plugin not scanning VS Solutions

### ISSUE THREAD

**Issue by tsn2022** [jenkinsci/fortify-plugin#53]
I'm unable to get the Fortify plugin to scan C++ Visual Studio solutions properly. The translation step is not finding the system VS dependencies (string, iostream, etc) or other dependencies in the project. Can you assist?

**Comment by akaryakina** [comment]
This seems to be something you should talk to the Fortify SCA support team, not the Jenkins plugin. Please, contact Fortify SCA support at: https://www.microfocus.com/en-us/support/Fortify%20Static%20Code%20Analyzer
