### ISSUE TITLE
unnesesary dependencies

### ISSUE THREAD

**Issue by umlublin** [jenkinsci/fortify-plugin#65]
### Jenkins and plugins versions report

not connected to issue

### What Operating System are you using (both controller, and any agents involved in the problem)?

any

### Reproduction steps

In 22.1.38 version of plugin there are many unnessary dependencies in *.hpi (examples)
- openapi-generator-5.2.1.jar
- rhino-1.7.7.2.jar
- jackson-datatype-joda-2.10.1.jar
and duplicated & conflicting dependencies:
swagger-core-1.6.2.jar
swagger-core-2.1.2.jar

### Expected Results

- smaller *.hpi
- only nessesary dependencies
- not cause conflicts in Jenkins (ex. with gitlab-api plugin)

### Actual Results

- 5 times larger *.hpi as previous version
- conflicts with gitlab-api plugin

**Comment by umlublin** [comment]
One part/level of this problem is here https://github.com/fortify/ssc-restapi-client/issues/39

**Comment by akaryakina** [comment]
Please, use 23.1.2

**Comment by akaryakina** [comment]
Sorry, closed the wrong issue.
